"""initial_schema

Revision ID: 54ef794f73b9
Revises: 
Create Date: 2026-04-12 18:21:08.948156
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ef794f73b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('cref_number', sa.String(length=30), nullable=False),
    sa.Column('cref_status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', 'REJECTED', name='crefstatus'), nullable=False),
    sa.Column('cref_verified_at', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('specialties', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('coverage_neighborhoods', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('max_travel_radius_km', sa.Float(), nullable=True),
    sa.Column('base_price_per_session', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operational_status', sa.Enum('PENDING_REVIEW', 'ACTIVE', 'SUSPENDED', 'INACTIVE', name='traineroperationalstatus'), nullable=False),
    sa.Column('avg_rating', sa.Float(), server_default='0', nullable=False),
    sa.Column('acceptance_rate', sa.Float(), server_default='1', nullable=False),
    sa.Column('attendance_rate', sa.Float(), server_default='1', nullable=False),
    sa.Column('total_sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cref_number'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('session_requests',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('requested_time_start', sa.Time(), nullable=False),
    sa.Column('requested_time_end', sa.Time(), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('venue_type', sa.Enum('GYM', 'OUTDOOR', 'HOTEL', 'RESIDENCE', 'FLEXIBLE', name='venuetype'), nullable=False),
    sa.Column('venue_details', sa.Text(), nullable=True),
    sa.Column('modality', sa.Enum('STRENGTH', 'FUNCTIONAL', 'RUNNING', 'YOGA', 'PILATES', 'STRETCHING', 'OTHER', name='modality'), nullable=False),
    sa.Column('urgency', sa.Enum('STANDARD', 'URGENT', name='urgency'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lead_source', sa.Enum('LANDING_PAGE', 'WHATSAPP', 'REFERRAL', 'PARTNER', name='leadsource'), nullable=False),
    sa.Column('lead_channel', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'MATCHING', 'AWAITING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='sessionrequeststatus'), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_availabilities',
    sa.Column('trainer_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('recurrence_type', sa.Enum('WEEKLY', 'ONE_TIME', name='recurrencetype'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('CANDIDATE', 'OFFERED', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='matchstatus'), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operated_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['session_requests.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time_start', sa.Time(), nullable=False),
    sa.Column('scheduled_time_end', sa.Time(), nullable=False),
    sa.Column('venue_type', sa.Enum('GYM', 'OUTDOOR', 'HOTEL', 'RESIDENCE', 'FLEXIBLE', name='venuetype'), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_address', sa.String(length=500), nullable=True),
    sa.Column('venue_notes', sa.Text(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('convenience_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trainer_payout_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['session_requests.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('incidents',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('reported_by', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('NO_SHOW_TRAINER', 'NO_SHOW_USER', 'QUALITY_COMPLAINT', 'SAFETY_ISSUE', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', name='incidentstatus'), nullable=False),
    sa.Column('impact_on_trainer', sa.Enum('NONE', 'WARNING', 'SUSPENSION', name='incidentimpact'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.Enum('PIX', 'CREDIT_CARD', 'PAYMENT_LINK', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('external_reference', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('payouts',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PAID', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('reviews',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('experience_tags', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('payouts')
    op.drop_table('payments')
    op.drop_table('incidents')
    op.drop_table('sessions')
    op.drop_table('matches')
    op.drop_table('trainer_availabilities')
    op.drop_table('session_requests')
    op.drop_table('users')
    op.drop_table('trainers')
    # ### end Alembic commands ###
